algoritmo "Escolha exemplo 1"
var
dia:inteiro
inicio
escreva("Digite um valor de 1 a 7: ")
leia(dia)
Escolha (dia)
caso 1
   escreva("Domingo")
caso 2
   escreva("Segunda-Feira")
caso 3
   escreva("Terça-Feira")
caso 4
   escreva("Quarta-Feira")
caso 5
   escreva("Quinta-Feira")
caso 6
   escreva("Sexta-Feira")
caso 7
   escreva("Sábado")
outroCaso
   escreva("Valor inválido")
fimEscolha
fimalgoritmo
