algoritmo "Calcular Produto"

var
 n1,n2,Produto,soma,subtracao,divisao:Real

inicio
//Entrada
  escreva("Digite um número: ")
  leia(n1)
  Escreva("Digite outro número: ")
  leia(n2)

  //processo
  Produto := n1*n2
  soma := n1+n2
  subtracao:= n1-n2
  divisao:= n1/n2
  //saida
  Escreval("Produto: ",produto)
  escreval("soma: ",soma)
  Escreval("subtração: ",subtracao)
  Escreval("divisão: ",divisao)

fimalgoritmo
